### ISSUE TITLE
Segfault in the OpenMHz Uploader plugin

### ISSUE THREAD

**Issue by mepholic** [robotastic/trunk-recorder#598]
Hello,

I'm working on testing trunk-recorder on Alpine Linux right now, hoping to get it merged from the testing repo to the community repo.

I've encountered a segfault from curl in the OpenMHz uploader plugin. A backtrace is included below:
```
Thread 818 "trunk-recorder" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 10605]
getinfo_long (param_longp=<optimized out>, info=CURLINFO_RESPONSE_CODE, data=0x7fffe27a7020) at getinfo.c:214
214     getinfo.c: No such file or directory.
(gdb) bt
#0  getinfo_long (param_longp=<optimized out>, info=CURLINFO_RESPONSE_CODE, data=0x7fffe27a7020) at getinfo.c:214
#1  Curl_getinfo (data=0x7fffe27a7020, info=CURLINFO_RESPONSE_CODE) at getinfo.c:577
#2  0x00007ffff4060974 in curl_easy_getinfo (data=<optimized out>, info=<optimized out>) at easy.c:760
#3  0x00007ffff40d64c4 in Openmhz_Uploader::upload (this=this@entry=0x7ffff40fe6e0, call_info=...) at /home/mepholic/aports/testing/trunk-recorder/src/trunk-recorder-4.2.2/plugins/openmhz_uploader/openmhz_uploader.cc:261
#4  0x00007ffff40d6be9 in Openmhz_Uploader::call_end (this=this@entry=0x7ffff40fe6e0, call_info=...) at /home/mepholic/aports/testing/trunk-recorder/src/trunk-recorder-4.2.2/plugins/openmhz_uploader/openmhz_uploader.cc:277
#5  0x00005555555d4e2f in plugman_call_end (call_info=...) at /home/mepholic/aports/testing/trunk-recorder/src/trunk-recorder-4.2.2/trunk-recorder/plugin_manager/plugin_manager.cc:165
#6  0x00005555555d899c in upload_call_worker (call_info=...) at /home/mepholic/aports/testing/trunk-recorder/src/trunk-recorder-4.2.2/trunk-recorder/call_concluder/call_concluder.cc:206
#7  0x00005555555db657 in std::__invoke_impl<Call_Data_t, Call_Data_t (*)(Call_Data_t), Call_Data_t> (__f=<optimized out>, __f=<optimized out>) at /usr/include/c++/11.2.1/bits/invoke.h:61
#8  std::__invoke<Call_Data_t (*)(Call_Data_t), Call_Data_t> (__fn=<optimized out>, __fn=<optimized out>) at /usr/include/c++/11.2.1/bits/invoke.h:97
#9  std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >::_M_invoke<0ul, 1ul> (this=<optimized out>) at /usr/include/c++/11.2.1/bits/std_thread.h:253
#10 std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >::operator() (this=<optimized out>) at /usr/include/c++/11.2.1/bits/std_thread.h:260
#11 std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<Call_Data_t>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >, Call_Data_t>::operator() (this=0x7fffe2688568)
    at /usr/include/c++/11.2.1/future:1386
#12 0x00005555555db759 in std::__invoke_impl<std::unique_ptr<std::__future_base::_Result<Call_Data_t>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<Call_Data_t>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >, Call_Data_t>&> (__f=...) at /usr/include/c++/11.2.1/bits/invoke.h:61
#13 std::__invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<Call_Data_t>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >, Call_Data_t>&> (__fn=...) at /usr/include/c++/11.2.1/bits/invoke.h:143
#14 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<Call_Data_t>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<Call_Data_t (*)(Call_Data_t), Call_Data_t> >, Call_Data_t> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/11.2.1/bits/std_function.h:291
#15 0x00005555555da89b in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>) at /usr/include/c++/11.2.1/bits/std_function.h:590
#16 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x7ffff43b5570, __f=<optimized out>, __did_set=0x7fffe26884ef) at /usr/include/c++/11.2.1/future:571
#17 0x00007ffff7fbb332 in ?? () from /lib/ld-musl-x86_64.so.1
#18 0x0000000000000000 in ?? ()
```

**Comment by mepholic** [comment]
#601 should resolve this
