### ISSUE TITLE
conventionalDMR failures on distros with hardening

### ISSUE THREAD

**Issue by ZeroChaos-** [robotastic/trunk-recorder#779]
I recently updated TR to latest master on my gentoo system and hit some errors which have been discussed in discord already.

It looks like in part that gnuradio has some bugs https://github.com/gnuradio/gnuradio/issues/6547

Additionally, I suspect that there may be some TR bugs around here:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 193 "frame_assemble8" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffe0cfa96c0 (LWP 17721)]
0x00007ffff68b178c in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff68b178c in ?? () from /lib64/libc.so.6
#1  0x00007ffff68619e6 in raise () from /lib64/libc.so.6
#2  0x00007ffff684b7fc in abort () from /lib64/libc.so.6
#3  0x00007ffff6adac7f in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#4  0x00007ffff7f4d417 in std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (__n=<optimized out>, this=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/stl_vector.h:1123
#5  dmr_slot::decode_vlch (this=0x5555559ef0d0, vlch=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:566
#6  0x00007ffff7f4ea4a in dmr_slot::decode_slot_type (this=this@entry=0x5555559ef0d0)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:171
#7  0x00007ffff7f4ee89 in dmr_slot::load_slot (this=0x5555559ef0d0, slot=slot@entry=0x5555559eefc8 "", sl_type=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:121
#8  0x00007ffff7f44b40 in dmr_cai::load_frame (this=this@entry=0x5555559eefb0, fr_sym=fr_sym@entry=0x5555559d7aa5 "", unmute=@0x7ffe0cfa7a4e: false)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_cai.cc:138
#9  0x00007ffff7f3cc06 in gr::op25_repeater::rx_sync::rx_sym (this=0x5555559d74d0, sym=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/rx_sync.cc:555
#10 0x00007ffff7ed4dda in gr::op25_repeater::frame_assembler_impl::general_work (this=0x5555559d6d50, noutput_items=<optimized out>, 
    ninput_items=std::vector of length 1, capacity 1 = {...}, input_items=..., output_items=std::vector of length 2, capacity 2 = {...})
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/frame_assembler_impl.cc:124
#11 0x00007ffff7128039 in gr::block_executor::run_one_iteration (this=this@entry=0x7ffe0cfa8888)
    at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/block_executor.cc:622
#12 0x00007ffff715bfe5 in gr::tpb_thread_body::tpb_thread_body (this=this@entry=0x7ffe0cfa8888, block=std::shared_ptr<gr::block> (use count 11, weak count 4) = {...}, 
    start_sync=std::shared_ptr<boost::barrier> (use count 482, weak count 0) = {...}, max_noutput_items=max_noutput_items@entry=32768)
    at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/tpb_thread_body.cc:94
#13 0x00007ffff715492c in gr::tpb_container::operator() (this=this@entry=0x555555ee6180)
    at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/scheduler_tpb.cc:38
#14 0x00007ffff7155244 in gr::thread::thread_body_wrapper<gr::tpb_container>::operator() (this=0x555555ee6180)
    at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/../include/gnuradio/thread/thread_body_wrapper.h:49
#15 0x00007ffff7bcb22e in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:179
#16 0x00007ffff68afa7d in ?? () from /lib64/libc.so.6
#17 0x00007ffff6930f80 in ?? () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff68b178c in ?? () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff68619e6 in raise () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff684b7fc in abort () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff6adac7f in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff7f4d417 in std::vector<unsigned char, std::allocator<unsigned char> >::operator[] (__n=<optimized out>, this=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/bits/stl_vector.h:1123
        __PRETTY_FUNCTION__ = <optimized out>
#5  dmr_slot::decode_vlch (this=0x5555559ef0d0, vlch=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:566
        i = <optimized out>
        rs_errs = 0
        rc = true
        lc_msg = "\000\000\000\377\377\340\000\000\001\000\000"
#6  0x00007ffff7f4ea4a in dmr_slot::decode_slot_type (this=this@entry=0x5555559ef0d0)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:171
        vlch = '\000' <repeats 24 times>, '\001' <repeats 19 times>, '\000' <repeats 28 times>, "\001\001\000\001\000\001\001\000\000\001\000\000\000\000\000\001\001\001\000\000\001\001\001\000\001"
        rc = true
        gly_errs = 0
        slot_cc = <optimized out>
#7  0x00007ffff7f4ee89 in dmr_slot::load_slot (this=0x5555559ef0d0, slot=slot@entry=0x5555559eefc8 "", sl_type=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:121
        is_voice_frame = false
        v_type = ""
#8  0x00007ffff7f44b40 in dmr_cai::load_frame (this=this@entry=0x5555559eefb0, fr_sym=fr_sym@entry=0x5555559d7aa5 "", unmute=@0x7ffe0cfa7a4e: false)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_cai.cc:138
        sync_rxd = <optimized out>
        sl_sync = <optimized out>
#9  0x00007ffff7f3cc06 in gr::op25_repeater::rx_sync::rx_sym (this=0x5555559d74d0, sym=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/rx_sync.cc:555
        bitbuf = '\000' <repeats 1193 times>...
        sync_detected = <optimized out>
        unmute = false
        tmpcw = '\000' <repeats 143 times>
        ysf_fullrate = false
        excess_count = 0
        start_idx = <optimized out>
        __PRETTY_FUNCTION__ = "virtual void gr::op25_repeater::rx_sync::rx_sym(uint8_t)"
        symbol_ptr = 0x5555559d7aa5 ""
        bit_ptr = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
#10 0x00007ffff7ed4dda in gr::op25_repeater::frame_assembler_impl::general_work (this=0x5555559d6d50, noutput_items=<optimized out>, ninput_items=std::vector of length 1, capacity 1 = {...}, input_items=..., output_items=std::vector of length 2, capacity 2 = {...}) at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/frame_assembler_impl.cc:124
        i = <optimized out>
        in = 0x7ffff1b0f389 "\001\002\001\002"
        amt_produce = <optimized out>
#11 0x00007ffff7128039 in gr::block_executor::run_one_iteration (this=this@entry=0x7ffe0cfa8888) at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/block_executor.cc:622
        i = <optimized out>
        n = <optimized out>
        msg = <optimized out>
        try_again = <optimized out>
        noutput_items = 1
        max_items_avail = 1
        max_noutput_items = <optimized out>
        new_alignment = 0
        alignment_state = <optimized out>
        output_idx = 0
        m = 0x5555559d6e18
        d = 0x555555dd50f0
#12 0x00007ffff715bfe5 in gr::tpb_thread_body::tpb_thread_body (this=this@entry=0x7ffe0cfa8888, block=std::shared_ptr<gr::block> (use count 11, weak count 4) = {...}, start_sync=std::shared_ptr<boost::barrier> (use count 482, weak count 0) = {...}, max_noutput_items=max_noutput_items@entry=32768) at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/tpb_thread_body.cc:94
        s = <optimized out>
        msg = std::shared_ptr<pmt::pmt_base> (empty) = {get() = 0x0}
        max_nmsgs = 8192
        logger = {_name = "tpb_thread_body", d_logger = std::shared_ptr<spdlog::logger> (use count 1, weak count 0) = {get() = 0x7fffe00017e0}}
        d = 0x555555dd50f0
        p = <optimized out>
        d = <optimized out>
        s = <optimized out>
        msg = <optimized out>
        p = <optimized out>
        max_nmsgs = <optimized out>
        logger = <optimized out>
        i = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        guard = <optimized out>
        timeout = <optimized out>
        guard = <optimized out>
#13 0x00007ffff715492c in gr::tpb_container::operator() (this=this@entry=0x555555ee6180) at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/scheduler_tpb.cc:38
        body = {d_exec = {d_block = std::shared_ptr<gr::block> (use count 11, weak count 4) = {get() = 0x5555559d6e18}, d_logger = std::shared_ptr<gr::logger> (use count 1, weak count 0) = {get() = 0x7fffe0001430}, d_debug_logger = std::shared_ptr<gr::logger> (use count 1, weak count 0) = {get() = 0x7fffe40018f0}, d_ninput_items_required = std::vector of length 1, capacity 1 = {1}, d_ninput_items = std::vector of length 1, capacity 1 = {1}, d_input_items = std::vector of length 1, capacity 1 = {0x7ffff1b0f389}, d_input_done = std::vector<bool> of length 1, capacity 64 = {false}, d_output_items = std::vector of length 2, capacity 2 = {0x7ffff1ae3000, 0x7ffff1ac1000}, d_start_nitems_read = std::vector of length 1, capacity 1 = {41865}, d_returned_tags = std::vector of length 0, capacity 1, d_max_noutput_items = 32768}}
#14 0x00007ffff7155244 in gr::thread::thread_body_wrapper<gr::tpb_container>::operator() (this=0x555555ee6180) at /var/tmp/portage/net-wireless/gnuradio-3.10.5.1/work/gnuradio-3.10.5.1/gnuradio-runtime/lib/../include/gnuradio/thread/thread_body_wrapper.h:49
No locals.
#15 0x00007ffff7bcb22e in boost::(anonymous namespace)::thread_proxy (param=<optimized out>) at libs/thread/src/pthread/thread.cpp:179
        thread_info = {px = 0x555555ee6200, pn = {pi_ = 0x555555ee60d0}}
        lock = {m = @0x0}
#16 0x00007ffff68afa7d in ?? () from /lib64/libc.so.6
No symbol table info available.
#17 0x00007ffff6930f80 in ?? () from /lib64/libc.so.6
No symbol table info available.
(gdb) p d_lc
No symbol "d_lc" in current context.
(gdb) frame 5
#5  dmr_slot::decode_vlch (this=0x5555559ef0d0, vlch=<optimized out>)
    at /var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc:566
566	/var/tmp/portage/net-wireless/trunk-recorder-9999/work/trunk-recorder-9999/lib/op25_repeater/lib/dmr_slot.cc: No such file or directory.
(gdb) p d_lc
$1 = std::vector of length 9, capacity 12 = {0 '\000', 0 '\000', 0 '\000', 255 '\377', 255 '\377', 224 '\340', 0 '\000', 0 '\000', 1 '\001'}
```

**Comment by faultywarrior** [comment]
Adding here what I mentioned in Discord to help those troubleshooting the code behind this issue- it impacts T-R as a whole.  P25 configs will also blow up with the same out of bounds error.  Confirmed that adding the cmake flag from #780 on Fedora 36 will trip this as well.
